In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
mental_df = pd.read_csv('Mental_Health_Dataset.csv')

In [6]:
mental_df.drop_duplicates(inplace= True)


In [7]:
mental_df.drop(columns='Timestamp',inplace=True)

In [8]:
mental_df.dropna(inplace=True)

In [9]:
col=mental_df.columns

In [10]:
col


Index(['Gender', 'Country', 'Occupation', 'self_employed', 'family_history',
       'treatment', 'Days_Indoors', 'Growing_Stress', 'Changes_Habits',
       'Mental_Health_History', 'Mood_Swings', 'Coping_Struggles',
       'Work_Interest', 'Social_Weakness', 'mental_health_interview',
       'care_options'],
      dtype='object')

In [11]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
encoder = LabelEncoder()

# Apply encoding to all columns
df_enc =pd.DataFrame( mental_df.apply(lambda col: encoder.fit_transform(col) if col.dtypes == 'object' else col))

df_enc
print("AFTER LABEL ENCODING:")
column=df_enc.columns.tolist()
for i in column:
    print(df_enc[i].unique())


AFTER LABEL ENCODING:
[0 1]
[34 25  0  4 33 29 30 22 21 15  1 16 11 26  3  6 27 13 31 10 17 18  2 28
 23  7 32  9 19 14 20  5 12  8 24]
[1 4 0 2 3]
[0 1]
[1 0]
[1 0]
[0 3 4 1 2]
[2 1 0]
[1 2 0]
[2 1 0]
[2 1 0]
[0 1]
[1 0 2]
[2 1 0]
[0 1 2]
[2 1 0]


In [12]:

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, roc_auc_score


In [13]:
X = df_enc.drop(columns='treatment')
y = df_enc['treatment']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
import joblib
import pickle
model = GradientBoostingClassifier()

model.fit(X_train, y_train)

# Save the model
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [26]:
import sklearn
print(sklearn.__version__)


1.4.2
